//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkedPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AssignedFlight
    {
        public int id { get; set; }
        [Required]
        public int flight_number { get; set; }
        [Required]
        public System.DateTime flight_date { get; set; }
        public string captain { get; set; }
        public string first_officer { get; set; }
        public string fal { get; set; }
        public string fa1 { get; set; }
        public string fa2 { get; set; }
        public string fa3 { get; set; }
        public string fa4 { get; set; }
        public string fa5 { get; set; }
    }
}
